# Generated by Django 2.2 on 2020-05-21 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iphone', models.CharField(max_length=64, verbose_name='手机号')),
                ('info', models.TextField(verbose_name='用户个人简介')),
                ('motto', models.CharField(max_length=128, verbose_name='用户个性签名')),
                ('photo', models.ImageField(upload_to='', verbose_name='用户照片')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User表外键')),
            ],
        ),
    ]
