# Generated by Django 2.2 on 2020-06-09 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judger_problem', '0013_delete_classrecode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRecode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建上课记录时间')),
                ('recode_time', models.DateTimeField(verbose_name='排的上课时间')),
                ('recode_states', models.IntegerField(choices=[(0, '未上课'), (1, '取消'), (2, '已上课')], verbose_name='上课记录的状态')),
                ('recode_video', models.CharField(max_length=128, verbose_name='上课视频地址')),
                ('recode_enter', models.CharField(max_length=128, verbose_name='上课入口地址')),
                ('fk_homework', models.ManyToManyField(related_name='homework_recode', to='judger_problem.Problem', verbose_name='作业题目')),
                ('fk_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上课教师')),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_recode', to=settings.AUTH_USER_MODEL, verbose_name='用户名')),
            ],
            options={
                'verbose_name': '上课记录',
                'verbose_name_plural': '上课记录',
            },
        ),
    ]
