# Generated by Django 2.2 on 2020-06-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200609_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrecode',
            name='recode_states',
            field=models.IntegerField(choices=[(0, '未上课'), (1, '取消'), (2, '已上课')], default=0, verbose_name='上课记录的状态'),
        ),
    ]
