# Generated by Django 2.2 on 2020-06-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200609_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrecode',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='讲师点评'),
        ),
    ]
