# Generated by Django 2.2 on 2020-06-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200609_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='classrecode',
            name='tiquma',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='视频提取码'),
        ),
    ]
