# Generated by Django 3.0.7 on 2020-06-12 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0007_classrecode_tiquma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrecode',
            name='fk_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上课讲师'),
        ),
        migrations.AlterField(
            model_name='classrecode',
            name='fk_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_recode', to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
    ]
