# Generated by Django 3.0.7 on 2020-07-28 09:54

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200612_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrecode',
            name='comment',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
