# Generated by Django 3.0.7 on 2020-08-05 06:17

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200728_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classrecode',
            name='comment',
            field=mdeditor.fields.MDTextField(blank=True, default='', verbose_name='讲师点评'),
        ),
    ]
