# Generated by Django 3.0.7 on 2020-08-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judger_problem', '0021_auto_20200808_0809'),
        ('account', '0010_auto_20200805_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='right_problems',
            field=models.ManyToManyField(to='judger_problem.Problem', verbose_name='正确题目列表'),
        ),
    ]
