# Generated by Django 2.2 on 2020-05-21 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='题目标题')),
                ('problem_content', models.TextField(verbose_name='题目内容')),
                ('problem_input', models.CharField(max_length=128, verbose_name='样例输入')),
                ('problem_output', models.CharField(max_length=128, verbose_name='样例输出')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建题目时间')),
                ('fk_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
        ),
        migrations.CreateModel(
            name='SubmitStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code_dir', models.CharField(max_length=128, verbose_name='用户代码路径')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='提交代码时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('fk_problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judger_problem.Problem', verbose_name='外键题目id')),
            ],
        ),
    ]
