# Generated by Django 2.2 on 2020-05-21 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('judger_problem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='Submits',
            field=models.IntegerField(default=0, verbose_name='总的用户提交次数'),
        ),
        migrations.AddField(
            model_name='problem',
            name='corrects',
            field=models.IntegerField(default=0, verbose_name='总的用户正确次数'),
        ),
        migrations.AddField(
            model_name='problem',
            name='difficulty',
            field=models.IntegerField(choices=[(0, '简单'), (1, '中等'), (2, '困难')], null=True, verbose_name='难度'),
        ),
        migrations.AddField(
            model_name='problem',
            name='explains',
            field=models.IntegerField(default=0, verbose_name='题目题解数量'),
        ),
        migrations.CreateModel(
            name='ProblemLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='标签名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='标签创建题目时间')),
                ('fk_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='fk_labels',
            field=models.ManyToManyField(to='judger_problem.ProblemLabel', verbose_name='题目标签'),
        ),
    ]
