# Generated by Django 2.2 on 2020-05-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judger_problem', '0002_auto_20200521_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='fk_labels',
            field=models.ManyToManyField(choices=[(0, '简单'), (1, '中等'), (2, '困难')], to='judger_problem.ProblemLabel', verbose_name='题目标签'),
        ),
    ]
