# Generated by Django 2.2 on 2020-05-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judger_problem', '0003_auto_20200522_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='fk_labels',
            field=models.ManyToManyField(choices=[(1, '动态'), (2, '语法')], to='judger_problem.ProblemLabel', verbose_name='题目标签'),
        ),
    ]
