# Generated by Django 2.2 on 2020-05-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judger_problem', '0004_auto_20200522_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'verbose_name': '题目列表', 'verbose_name_plural': '题目列表'},
        ),
        migrations.AlterModelOptions(
            name='problemlabel',
            options={'verbose_name': '题目标签', 'verbose_name_plural': '题目标签'},
        ),
        migrations.AlterModelOptions(
            name='submitstatus',
            options={'verbose_name': '提交状态', 'verbose_name_plural': '提交状态'},
        ),
        migrations.RemoveField(
            model_name='submitstatus',
            name='user_code_dir',
        ),
        migrations.AddField(
            model_name='submitstatus',
            name='user_code_content',
            field=models.CharField(default='', max_length=128, verbose_name='用户代码'),
        ),
        migrations.AddField(
            model_name='submitstatus',
            name='user_code_status',
            field=models.IntegerField(choices=[(0, '答案正确'), (1, '答案错误'), (2, '判题中'), (3, '无法运行')], null=True, verbose_name='提交状态'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='fk_labels',
            field=models.ManyToManyField(to='judger_problem.ProblemLabel', verbose_name='题目标签'),
        ),
    ]
