# Generated by Django 2.2 on 2020-05-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judger_problem', '0007_auto_20200527_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='fk_labels',
            field=models.ManyToManyField(related_name='problem', to='judger_problem.ProblemLabel', verbose_name='题目标签'),
        ),
    ]
