# Generated by Django 2.2 on 2020-05-28 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('judger_problem', '0008_auto_20200528_0616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='保存笔记的时间')),
                ('content', models.CharField(max_length=1024, verbose_name='笔记内容')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('fk_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judger_problem.Problem', verbose_name='题目')),
            ],
        ),
    ]
