# Generated by Django 2.2 on 2020-06-05 08:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('judger_problem', '0010_problem_fk_liked_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='fk_collect_user',
            field=models.ManyToManyField(related_name='collect_user', to=settings.AUTH_USER_MODEL, verbose_name='收藏的用户'),
        ),
    ]
