# Generated by Django 2.2 on 2020-06-09 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judger_problem', '0012_classrecode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassRecode',
        ),
    ]
