# Generated by Django 3.0.7 on 2020-06-15 04:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('judger_problem', '0015_auto_20200615_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='fk_collect_user',
            field=models.ManyToManyField(null=True, related_name='collect_user', to=settings.AUTH_USER_MODEL, verbose_name='收藏的用户'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='fk_labels',
            field=models.ManyToManyField(null=True, related_name='problem', to='judger_problem.ProblemLabel', verbose_name='题目标签'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='fk_liked_user',
            field=models.ManyToManyField(null=True, related_name='liked_user', to=settings.AUTH_USER_MODEL, verbose_name='点赞的用户'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_std_code',
            field=models.TextField(default='', null=True, verbose_name='标准代码'),
        ),
    ]
