# Generated by Django 3.0.7 on 2020-06-15 04:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('judger_problem', '0016_auto_20200615_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='Submits',
            field=models.IntegerField(blank=True, default=0, verbose_name='总的用户提交次数'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='corrects',
            field=models.IntegerField(blank=True, default=0, verbose_name='总的用户正确次数'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.IntegerField(blank=True, choices=[(0, '简单'), (1, '中等'), (2, '困难')], null=True, verbose_name='难度'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='explains',
            field=models.IntegerField(blank=True, default=0, verbose_name='题目题解数量'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='fk_collect_user',
            field=models.ManyToManyField(blank=True, null=True, related_name='collect_user', to=settings.AUTH_USER_MODEL, verbose_name='收藏的用户'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='fk_labels',
            field=models.ManyToManyField(blank=True, related_name='problem', to='judger_problem.ProblemLabel', verbose_name='题目标签'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='fk_liked_user',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_user', to=settings.AUTH_USER_MODEL, verbose_name='点赞的用户'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_std_code',
            field=models.TextField(blank=True, default='', verbose_name='标准代码'),
        ),
    ]
