# Generated by Django 3.0.7 on 2020-06-15 04:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('judger_problem', '0017_auto_20200615_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='fk_collect_user',
            field=models.ManyToManyField(blank=True, related_name='collect_user', to=settings.AUTH_USER_MODEL, verbose_name='收藏的用户'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='fk_liked_user',
            field=models.ManyToManyField(blank=True, related_name='liked_user', to=settings.AUTH_USER_MODEL, verbose_name='点赞的用户'),
        ),
    ]
