# Generated by Django 3.0.7 on 2020-06-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judger_problem', '0019_auto_20200615_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problem_input_style',
            field=models.TextField(default='', verbose_name='输入格式'),
        ),
        migrations.AddField(
            model_name='problem',
            name='problem_output_style',
            field=models.TextField(default='', verbose_name='输出格式'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_input',
            field=models.TextField(verbose_name='样例输入'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_output',
            field=models.TextField(verbose_name='样例输出'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_test_case_input',
            field=models.TextField(default='', help_text="以'///'分割多个数据", verbose_name='输入测试用例'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_test_case_output',
            field=models.TextField(default='', help_text="以'///'分割多个数据", verbose_name='输出测试用例'),
        ),
    ]
