# Generated by Django 3.0.7 on 2020-08-08 08:09

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('judger_problem', '0020_auto_20200615_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='problem_content',
            field=mdeditor.fields.MDTextField(verbose_name='题目内容'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_input',
            field=models.TextField(blank=True, verbose_name='样例输入'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_input_style',
            field=models.TextField(blank=True, default='', verbose_name='输入格式'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_output',
            field=models.TextField(blank=True, verbose_name='样例输出'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_output_style',
            field=models.TextField(blank=True, default='', verbose_name='输出格式'),
        ),
    ]
